### ISSUE TITLE
日英のリソース構成について

### ISSUE THREAD

**Issue by kitkatayama** [weseek/growi-docs#3]
翻訳を試みようと思いましたが、全体の構成に疑問を持ったのでissueを発行させていただきます。

## ディレクトリ構成について

GitHub上のリソースの構成を、以下のように変更するのはいかがでしょうか。

### 変更前構成

```
weseek/growi-docs
- docs
  + api
  + dev
  + guide
  - ja
    + dev
    + guide
```

### 変更後構成

```
weseek/growi-docs
- docs
  - en
    + dev
    + guide
    + api
    ...
  - ja
    + dev
    + guide
    + api
    ...
```

### 構成変更による影響

GitHub上の構成だけでなく、URLも以下のように変更されるかと考えていますが、日英だけでなく、複数言語対応するのであれば、都合も良いのではないかと考えています。

    https://docs.growi.org/{locale}

つまり、現状では以下のように変更されると考えております。

* 現在
  * 英: https://docs.growi.org/
  * 日: https://docs.growi.org/ja/
* 変更後
  * 英: https://docs.growi.org/en/
  * 日: https://docs.growi.org/ja/

以上となります。

**Comment by yuki-takei** [comment]
@kitkatayama ご提案ありがとうございます。

個人的にもその方が気持ちいいというのには同意なのですが、使っている VuePress 本家(https://vuepress.vuejs.org/) も、また別の static site generator のドキュメント(例えば https://hexo.io/docs/) も同じようなツリー構造になっているので、そこは慣習なのかなと思っています。

**Comment by yuki-takei** [comment]
翻訳のPRはお待ちしております！
