### ISSUE TITLE
GROWI独自形式のページリンクの説明をわかりやすくしてほしい

### ISSUE THREAD

**Issue by noymer** [weseek/growi-docs#306]
以下部分がよくわからなかったので、わかりやすく書いてほしい。
https://github.com/weseek/growi-docs/blob/49d81f6ef89eb5f27493da3941d1063fcdd42a37/docs/ja/guide/tips/page_linker.md?plain=1#L21-L31

具体的に良くわからなかったのは、`[` `]`を使うリンクの書き方と、 `&lt;` `>` を使うリンクの書き方の2パターンあるという事なのか、それともすべての説明で一つの書き方になっているのか、二行の関係性が良くわからないこと。

また一行目は「パス」という用語を、二行目は「配下ページ」を使っており、その意味の違いもよくわからなかった。
https://github.com/weseek/growi/blob/v5.0.10/packages/app/src/client/util/PreProcessor/Linker.js を読む限り、どちらも絶対パスが必要で、二行目は `/` が二つ以上必要というのが違いのようだが、それが読み取れなかった。

また合わせて、 https://github.com/weseek/growi-docs/pull/116/files#r417594067 に書かれているように、[plugin-pukiwiki-like-linker](https://github.com/weseek/growi/tree/v5.0.10/packages/plugin-pukiwiki-like-linker) によるリンクの書き方も書いてあると良い。

**Comment by yasumichi** [comment]
https://github.com/weseek/growi-docs/blob/master/docs/ja/guide/features/page_linker.md

master では、「GROWI 独自方式」の記述が消えている状態ですが、そもそも独自形式がなくなったのでしょうか？ > 開発者の皆様

**Comment by yuki-takei** [comment]
v6.0 で廃止されました

[GROWI v6.0.x へのアップグレード >  [廃止を伴う仕様変更] GROWI 独自記法のページリンク](https://docs.growi.org/ja/admin-guide/upgrading/60x.html#%E5%BB%83%E6%AD%A2%E3%82%92%E4%BC%B4%E3%81%86%E4%BB%95%E6%A7%98%E5%A4%89%E6%9B%B4-growi-%E7%8B%AC%E8%87%AA%E8%A8%98%E6%B3%95%E3%81%AE%E3%83%98%E3%82%9A%E3%83%BC%E3%82%B7%E3%82%99%E3%83%AA%E3%83%B3%E3%82%AF)

クローズします
