### ISSUE TITLE
Please update this docs' Install section.

### ISSUE THREAD

**Issue by MasaruKitajima** [weseek/growi-docs#343]
On the [English Page](https://docs.growi.org/en/admin-guide/getting-started/centos.html), it says;

> ## Overview
> 
> This chapter introduces the installation process for GROWI on CentOS 7. Installation on CentOS 6 has not been verified.
> 
> Software needed for Setup are listed below.
> 
> - Node.js 14.x (DO NOT USE 14.x)
> - npm 6.x
> - yarn
> - MongoDB 4.x
> - (Optional) Elasticsearch 6.x
> - (Optional) systemd
> - (Optional) Apache or nginx

The above mentions `Node.js 14.x`, but the next section is as follows.

> ## Installation for node.js 8.x & npm

But the sample code is

```bash
$ curl -sL https://rpm.nodesource.com/setup_14.x -o nodesource_setup.sh
```

This might confuse who tries to install.

I'm a Japanese, so I looked at the [Install](https://docs.growi.org/ja/admin-guide/getting-started/centos.html#overview), and it says;

> - node.js 8.x (DO NOT USE 9.x)
> - npm 6.x
> - yarn
> - MongoDB 3.x
> - (Optional) Elasticsearch 5.x
> - (Optional) systemd
> - (Optional) Apache or nginx

Following the instructions and when I tried to install `GROWI` by running `yarn,` it failed and said;

> $ yarn
> yarn install v1.22.19
> [1/5] Validating package.json...
> error growi@6.0.15: The engine "node" is incompatible with this module. Expected version "^14 || ^16". Got "8.17.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I'm so disappointed. I need to start all over again... GROWI's reputations in Japan are the highest, so I decided to install it, but unable...

Please update the document.

**Comment by yuki-takei** [comment]
@MasaruKitajima I'm sorry that I haven't been able to maintain the document.

Unfortunately, this document is not very reliable, as you can see from the warning at the beginning that "This article has been in the public domain for some time."

The reason is that the document was previously contributed by a user, so we GROWI developers team have not verified all of it and it is difficult to keep it up to date.

Thank you for your understanding.

**Comment by yuki-takei** [comment]
However, sending PR is welcome🙂
