### ISSUE TITLE
周辺ソフトウェアのバージョン要件が古い

### ISSUE THREAD

**Issue by shield-9** [weseek/growi-docs#42]
インストール手順がGROWI 3.3以前の状態のようです。

Elasticsearch 5.x系を入れるという指示が書いてありますが、最新だと6.x系に変わっています。
しっかりと確認していませんが、Elasticsearch以外も古いままのようです。

**Comment by yuki-takei** [comment]
@shield-9 ありがとうございます。議題に挙げて少しずつやっていきます。

**Comment by yuki-takei** [comment]
本日部分的にアップデートしました。
https://github.com/weseek/growi-docs/compare/e3d39c76b6d44eaca2e9dbb84ddb94aeb012546d..a8b1a8921cbabdf064404a6e24fa031ca7d2734c
