### ISSUE TITLE
CentOS の代わりに AlmaLinux へのインストール手順の追加

### ISSUE THREAD

**Issue by yasumichi** [weseek/growi-docs#461]
[CentOS | GROWI Docs](https://docs.growi.org/ja/admin-guide/getting-started/centos.html)がしばらく更新されていませんが、CentOS プロジェクトが終了したこともあり、代替の [AlmaLinux](https://almalinux.org/) または [Rocky Linux](https://rockylinux.org/)  など、RedHat 系の Linux へのインストール手順を追加した方が良いと考えます。

Google トレンドで見る限り、AlmaLinux が優勢のようです。可能であれば、Ubuntu Server の更新内容も取り込みつつ、AlmaLinux へのインストール手順を作成したいと存じます。いかがでしょうか？

**Comment by yuki-takei** [comment]
@yasumichi 提案ありがとうございます！大歓迎です！

**Comment by yasumichi** [comment]
#464 の Merge をもって、クローズします。
