### ISSUE TITLE
「開発環境の構築」において、credential helper のパスが　Git v2.36.1 未満のパスになっている

### ISSUE THREAD

**Issue by yasumichi** [weseek/growi-docs#482]
「[開発環境の構築](https://docs.growi.org/ja/dev/startup-v5/dev-env.html)」-「Git のインストール」-「設定」において、`# Windows の場合は、WSL 内から更にホストPCの credential helper を参照する設定を行う`のコマンドが、

```sh
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager-core.exe"
```

になっていますが、新しいバージョンの Git ではパスが異なっているようです。

## インストールされている GIT が >= v2.39.0 の場合

```sh
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
```

## またはインストールされている GIT が >= v2.36.1 の場合

```sh
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
```

## 参考リンク

[WSL で Git の使用を開始する | Microsoft Learn](https://learn.microsoft.com/ja-jp/windows/wsl/tutorials/wsl-git)

**Comment by yuki-takei** [comment]
ご指摘ありがとうございます。修正しました！
